name: "java-client-ci"

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - /^release-.*$/
    paths:
      - hugegraph-client/**
      - hugegraph-dist/**
      - .github/workflows/**
      - pom.xml
  pull_request:
    paths:
      - hugegraph-client/**
      - hugegraph-dist/**
      - .github/workflows/**
      - pom.xml

jobs:
  client-ci:
    runs-on: ubuntu-latest
    env:
      USE_STAGE: 'true' # Whether to include the stage repository.
      TRAVIS_DIR: hugegraph-client/assembly/travis
    strategy:
      fail-fast: false
      matrix:
        # released pd package is compiled in version 55.0, which requires java 11 to use
        JAVA_VERSION: [ '11' ]

    steps:
      - name: Fetch code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Get HugeGraph stable commit id
        id: get-commit
        uses: ./.github/actions/get-hugegraph-commit

      - name: Setup Java environment
        uses: ./.github/actions/setup-java-env
        with:
          java-version: ${{ matrix.JAVA_VERSION }}
          distribution: 'zulu'
          use-stage: ${{ env.USE_STAGE }}

      - name: Setup HugeGraph server
        uses: ./.github/actions/setup-hugegraph-server
        with:
          travis-dir: ${{ env.TRAVIS_DIR }}
          commit-id: ${{ steps.get-commit.outputs.commit_id }}

      - name: Compile
        run: |
          mvn -e compile -pl hugegraph-client -Dmaven.javadoc.skip=true -ntp

      - name: Run test
        run: |
          cd hugegraph-client && ls *
          mvn test -Dtest=UnitTestSuite -ntp
          mvn test -Dtest=ApiTestSuite
          mvn test -Dtest=FuncTestSuite

      - name: Upload coverage to Codecov
        uses: ./.github/actions/upload-coverage
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: target/jacoco.xml
