name: "java-client-ci"

on:
  workflow_call:
    inputs:
      server-repository:
        type: string
        default: apache/hugegraph
      artifact-name:
        type: string
        required: true
      server-commit:
        type: string
        required: true
      server-ref:
        type: string
        required: true

jobs:
  client-ci:
    runs-on: ubuntu-latest
    env:
      USE_STAGE: 'true' # Whether to include the stage repository.
      TRAVIS_DIR: hugegraph-client/assembly/travis
    strategy:
      fail-fast: false
      matrix:
        # released pd package is compiled in version 55.0, which requires java 11 to use
        JAVA_VERSION: ['11', '17']

    steps:
      - name: Fetch code
        uses: actions/checkout@v7
        with:
          fetch-depth: 2

      - name: Install released Server JVM
        id: server-java
        uses: actions/setup-java@v5
        with:
          java-version: '11'
          distribution: temurin
          overwrite-settings: false

      - name: Setup Java environment
        uses: ./.github/actions/setup-java-env
        with:
          java-version: ${{ matrix.JAVA_VERSION }}
          distribution: 'zulu'
          use-stage: ${{ env.USE_STAGE }}

      - name: Setup HugeGraph server
        uses: ./.github/actions/setup-hugegraph-server
        with:
          travis-dir: ${{ env.TRAVIS_DIR }}
          commit-id: ${{ inputs.server-commit }}
          repository: ${{ inputs.server-repository }}
          fetch-ref: ${{ inputs.server-ref }}
          artifact-name: ${{ inputs.artifact-name }}
          mode: start
          java-version: '11'
          java-home: ${{ steps.server-java.outputs.path }}

      - name: Compile
        run: |
          mvn -e compile -pl hugegraph-client -Dmaven.javadoc.skip=true -ntp

      - name: Run test
        run: |
          cd hugegraph-client && ls -- *
          mvn test -Dtest=UnitTestSuite -ntp
          mvn test -Dtest=ApiTestSuite
          mvn test -Dtest=FuncTestSuite

      - name: Upload coverage to Codecov
        uses: ./.github/actions/upload-coverage
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: hugegraph-client/target/jacoco.xml
