name: "hubble-ci"

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - /^release-.*$/
    paths:
      - hugegraph-hubble/**
      - hugegraph-dist/**
      - hugegraph-loader/**
      - .github/workflows/**
      - pom.xml
  pull_request:
    paths:
      - hugegraph-hubble/**
      - hugegraph-dist/**
      - hugegraph-loader/**
      - hugegraph-client/**
      - .github/workflows/**
      - pom.xml

env:
  TRAVIS_DIR: hugegraph-hubble/hubble-dist/assembly/travis

jobs:
  hubble-ci:
    runs-on: ubuntu-latest
    env:
      USE_STAGE: 'true' # Whether to include the stage repository.
      STATIC_DIR: hugegraph-hubble/hubble-dist/assembly/static
    strategy:
      matrix:
        JAVA_VERSION: ['11']
        python-version: ["3.11"]

    steps:
      - name: Fetch Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Get HugeGraph stable commit id
        id: get-commit
        uses: ./.github/actions/get-hugegraph-commit

      - name: Setup Java environment
        uses: ./.github/actions/setup-java-env
        with:
          java-version: ${{ matrix.JAVA_VERSION }}
          distribution: 'adopt'
          use-stage: ${{ env.USE_STAGE }}

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Set up Node.js 18.20.8
        uses: actions/setup-node@v4
        with:
          node-version: '18.20.8'

      # we also should cache python & yarn & downloads to avoid useless work
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Cache Node modules
        uses: actions/cache@v3
        with:
          path: |
            hugegraph-hubble/hubble-fe/node_modules
            hugegraph-hubble/hubble-fe/node
            ~/.cache/yarn
          key: ${{ runner.os }}-node-${{ hashFiles('**/package.json', '**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: use staged maven repo settings
        if: ${{ env.USE_STAGE == 'true' }}
        run: |
          cp $HOME/.m2/settings.xml /tmp/settings.xml
          mv -vf .github/configs/settings.xml $HOME/.m2/settings.xml

      - name: Compile
        run: |
          mvn install -pl hugegraph-client,hugegraph-loader -am -Dmaven.javadoc.skip=true -DskipTests -ntp
          cd hugegraph-hubble && ls *
          mvn -e compile -Dmaven.javadoc.skip=true -ntp

      - name: Prepare env and service
        env:
          CI: false
        run: |
          echo "=== Environment Info ==="
          node -v
          yarn -v
          echo "NODE_OPTIONS: $NODE_OPTIONS"
          echo "CI: $CI"
          free -h || true
          echo "======================="
          
          COMMIT_ID: ${{ steps.get-commit.outputs.commit_id }}
        run: |
          python -m pip install -r ${TRAVIS_DIR}/requirements.txt
          cd hugegraph-hubble
          mvn package -Dmaven.test.skip=true
          cd apache-hugegraph-hubble-*
          cd bin
          ./start-hubble.sh -d
          ./stop-hubble.sh
          cd ../../../
          pwd
          $TRAVIS_DIR/install-hugegraph.sh $COMMIT_ID

      - name: Unit test
        run: mvn test -P unit-test -pl hugegraph-hubble/hubble-be -ntp

      - name: API test
        env:
          CI: false
        run: |
          cd hugegraph-hubble && ls
          hubble-dist/assembly/travis/run-api-test.sh

      - name: Upload coverage to Codecov
        uses: ./.github/actions/upload-coverage
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: target/site/jacoco/*.xml
